Remove Stuff for Real

diff --git a/.github/workflows/reusable_workflow.yml b/.github/workflows/reusable_workflow.yml
--- a/.github/workflows/reusable_workflow.yml
+++ b/.github/workflows/reusable_workflow.yml
@@ -33,7 +33,8 @@ jobs:
       run: |
         ls -la /mnt || true
         df -h /mnt
-        docker system prune -af --volumes
+        sudo rm -rf /mnt/btrfs_loopbacks || true
+        sudo rm -rf /mnt/var-lib-docker || true
         df -h /mnt
     - name: Validate Inputs
       run: |
@@ -45,9 +46,9 @@ jobs:
             ;;
         esac
         case "${{ inputs.unreal_version }}" in
-          "5.4.4"|"5.5.4") ;;
+          "5.4"|"5.5"|"5.6") ;;
           *)
-            echo "Error: Invalid Unreal Version. Only 5.4.4 and 5.5.4 are supported."
+            echo "Error: Invalid Unreal Version. Only 5.4, 5.5 and 5.6 are supported."
             exit 1
             ;;
         esac
